### ISSUE TITLE
Crash on newest version

### ISSUE THREAD

**Issue by sternschnaube** [cattyngmd/ShulkerView#2]
java.lang.ArrayIndexOutOfBoundsException: Index 27 out of bounds for length 27
	at java.base/java.util.Arrays$ArrayList.set(Arrays.java:4170)
	at net.minecraft.class_2371.set(class_2371.java:54)
	at dev.cattyn.shulkerview.utils.ShulkerInfo.create(ShulkerInfo.java:35)
	at dev.cattyn.shulkerview.handler.UpdateHandler.tick(UpdateHandler.java:19)
	at net.minecraft.class_465.handler$lol010$shulker-view$tick(class_465.java:15712)
	at net.minecraft.class_465.method_25393(class_465.java)
	at net.minecraft.class_310.method_1572(class_310.java:1985)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_310.method_1574(class_310.java:1985)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by sternschnaube** [comment]
I use the mod Carpet AMS Addition for double sized shulkers.

https://modrinth.com/mod/carpet-ams-addition
